---
title: Fresher Foundry
timezone: Asia/Kolkata
collections:
  authors:
    title: Authors
    output: true
  collections:
    title: Collections
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: authors
  values:
    permalink: "/blog/authors/:title/"
    layout: author
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author: Aneesha Pillai
    featured image: 
email: aneesha@fresherfoundry.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
permalink: pretty
url: https://www.fresherfoundry.com
markdown: kramdown
gems:
- jekyll-seo-tag
- jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed
exclude:
- gulpfile.js
- Gemfile
- Gemfile.lock
- package.json
- README*
- node_modules
- ".gitignore"
facebook:
  publisher: https://www.facebook.com/fresherfoundry/
social:
  name: Fresher Foundry
  links:
  - https://www.facebook.com/fresherfoundry
phone: "+919819954714"
address: |-
  H-68, 0/2, <br>
  Sector - 4, Nerul,<br>
  Navi Mumbai - 400706
logo: "/uploads/logo-light.png"
paginate: 5
paginate_path: "/blog/page:num/"
