---
title: Future Foundry
timezone: Asia/Kolkata
collections:
  authors:
    title: Authors
    output: true
  categories:
    title: Categories
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: authors
  values:
    permalink: "/blog/authors/:title/"
    layout: author
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author: Aneesha Pillai
    featured image: 
    category: 
email: aneesha@futurefoundry.in
description: We help businesses adopt emerging technologies through roundtables, deep
  dive training, labs & project consultancy in IoT, Big Data, Blockchain, AI & Drones.
permalink: pretty
url: https://www.futurefoundry.in
markdown: kramdown
gems:
- jekyll-seo-tag
- jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed
exclude:
- gulpfile.js
- Gemfile
- Gemfile.lock
- package.json
- README*
- node_modules
- ".gitignore"
facebook:
  publisher: https://www.facebook.com/futurefoundryin/
social:
  name: Fresher Foundry
  links:
  - https://www.facebook.com/futurefoundryin/
  - https://www.linkedin.com/company/future-foundry
phone: "+91 9819954714"
address: |-
  H-68, 0/2, <br>
  Sector - 4, Nerul,<br>
  Navi Mumbai - 400706
logo: "/uploads/logo-dark.png"
alternative logo: "/uploads/logo-light-c2ea60.png"
paginate: 5
paginate_path: "/blog/page:num/"
linkedin: https://www.linkedin.com/company/future-foundry
notice text: 
