---
title: Fresher Foundry
timezone: Asia/Kolkata
collections:
  authors:
    title: Authors
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: aneesha@fresherfoundry.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
permalink: pretty
url: https://www.fresherfoundry.com
markdown: kramdown
gems:
- jekyll-seo-tag
- jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed
exclude:
- gulpfile.js
- Gemfile
- Gemfile.lock
- package.json
- README*
- node_modules
- ".gitignore"
facebook:
  publisher: https://www.facebook.com/fresherfoundry/
social:
  name: Fresher Foundry
  links:
  - https://www.facebook.com/fresherfoundry
